version: '3.7'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db_datos:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdd_tienda
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "80:80"

